# Generated by Django 3.1.4 on 2021-01-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='ended',
            field=models.BooleanField(default=False),
        ),
    ]
